### ISSUE TITLE
shopifyCheckout.getAllOrders() fails to execute

### ISSUE THREAD

**Issue by emvaized** [ThinkSimple/flutter_simple_shopify#35]
Here's the code I'm using:
```
String _accessToken = (await SharedPreferences.getInstance()).getString('FLUTTER_SIMPLE_SHOPIFY_ACCESS_TOKEN');
List<Order> _history = await shopifyCheckout.getAllOrders(_accessToken);
```

Error code:
```
E/flutter ( 1861): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: GraphQL Errors:
E/flutter ( 1861): Internal error. Looks like something went wrong on our end.
E/flutter ( 1861): Request ID: 1d7976c7-1489-4927-be3c-a626de01ba09 (include this in support requests).: Undefined location
E/flutter ( 1861): #0      ShopifyError.checkForError (package:flutter_simple_shopify/mixins/src/shopfiy_error.dart:6:7)
E/flutter ( 1861): #1      ShopifyCheckout.getAllOrders (package:flutter_simple_shopify/shopify/src/shopify_checkout.dart:70:7)
```

**Comment by ThinkSimple** [comment]
Hello, the problems seems to lie within the sort key, simply change it to a different one (not the RELEVANCE one !).
I will take out the problematic sort key in the next update!
