### ISSUE TITLE
Exception when no internet connection

### ISSUE THREAD

**Issue by nishiths23** [ThinkSimple/flutter_simple_shopify#5]
When there is no internet connection i get an exception, may be this is GraphQL library issue but i think in the app we should be able to handle simple network issues.

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
#2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
#3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
<asynchronous suspension>
#4      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart)
#5      _runGuarded (dart:async/stream_controller.dart:820:24)
#6      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:699:7)
#7      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417:13)
#8      _StreamController._subscribe (dart:async/stream_controller.dart:698:18)
#9      _ControllerStream._createSubscription (dart:async/stream<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
#2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
#3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
<asynchronous suspension>
#4      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart)
#5      _runGuarded (dart:async/stream_controller.dart:820:24)
#6      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:699:7)
#7      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417:13)
#8      _StreamController._subscribe (dart:async/stream_controller.dart:698:18)
#9      _ControllerStream._createSubscription (dart:async/stream<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
#2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
#3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
<asynchronous suspension>
#4      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart)
#5      _runGuarded (dart:async/stream_controller.dart:820:24)
#6      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:699:7)
#7      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417:13)
#8      _StreamController._subscribe (dart:async/stream_controller.dart:698:18)
#9      _ControllerStream._createSubscription (dart:async/stream<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
#2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
#3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
<asynchronous suspension>
#4      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart)
#5      _runGuarded (dart:async/stream_controller.dart:820:24)
#6      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:699:7)
#7      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417:13)
#8      _StreamController._subscribe (dart:async/stream_controller.dart:698:18)
#9      _ControllerStream._createSubscription (dart:async/stream<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
#2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
#3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
<asynchronous suspension>
#4      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart)
#5      _runGuarded (dart:async/stream_controller.dart:820:24)
#6      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:699:7)
#7      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417:13)
#8      _StreamController._subscribe (dart:async/stream_controller.dart:698:18)
#9      _ControllerStream._createSubscription (dart:async/stream<…>
```

**Comment by ThinkSimple** [comment]
Hey I've updated the Graphql library now and the exception now gives a more detailed error.
Do you have a specific way of handling this exception in mind or do you think a more detailed exception is enough?

**Comment by SimonIT** [comment]
I'm closing it for now because of no response from the original author.
If the issue does still persist, feel free to leave a comment and I will reopen the issue :)
